version: "3.5"

services:

  studies-mysql:
    container_name: studies-mysql
    image: mysql:5.7.24 #8.0.13
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=studiesdb
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=secret
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 10s

  studies-postgres:
    container_name: studies-postgres
    image: postgres:11.1
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=studiesdb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
    healthcheck:
      test: "pg_isready -U postgres"
      start_period: 10s