server.port: 8082

spring:
  application:
    name: jpa-locking
  jpa:
    hibernate:
      ddl-auto: update

#logging:
#  level:
#    org.hibernate:
#      SQL: DEBUG
#      type.descriptor.sql.BasicBinder: TRACE

---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/studiesdb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: secret

---
spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/studiesdb
    username: postgres
    password: postgres

---
spring:
  profiles: mysql-test
  datasource:
    url: jdbc:mysql://localhost:3307/test?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: test
    password: test

---
spring:
  profiles: postgres-test
  datasource:
    url: jdbc:postgresql://localhost:54322/test
    username: test
    password: test
