server.port: 8080

spring:
  application:
    name: jpa-associations
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://${MYSQL_ADDR:localhost}:3306/studiesdb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: secret

logging.level:
  org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE

---
spring:
  profiles: postgres
  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false # fix for exception: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented
  datasource:
    url: jdbc:postgresql://${POSTGRES_ADDR:localhost}:5432/studiesdb
    username: root
    password: secret
