server.port: 8085

spring:
  application:
    name: consumer
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/studiesdb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=true&serverTimezone=${application.server-timezone}&allowPublicKeyRetrieval=true
    username: root
    password: secret

application:
  server-timezone: UTC
