server.port: 8081

spring:
  application:
    name: jpa-batch
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 10

#logging:
#  level:
#    org.hibernate:
#      SQL: DEBUG
#      type.descriptor.sql.BasicBinder: TRACE

---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/studiesdb?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: secret

---
spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/studiesdb
    username: postgres
    password: postgres

---
spring:
  profiles: mysql-test
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    url:      # \
    username: #  ) they will be set dynamically by AbstractTestcontainers
    password: # /

---
spring:
  profiles: postgres-test
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    url:      # \
    username: #  ) they will be set dynamically by AbstractTestcontainers
    password: # /
